name: Github Actions Test

on:
  push:
    branches:
      - main


jobs:
  My-Deloy-Jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Hello World
        run: echo "Hello World"
      - name: Step check1( 여러 명령어작성)
        run: |
          echo "Good"
          echo "Hello"
      - name: Step check2(자체에 저장되어 있는 변수 확인)
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
      - name: Step check3(Github Actions Secret 변수)
        run: |
          echo ${{ secrets.MY_NAME }}
          echo ${{ secrets.MY_HOBBY }}